-- Sample candidate data for testing the candidate dashboard system
-- This will create test candidates with different profiles to test various features

-- Insert test candidate 1 - Complete profile
INSERT INTO `candidates`(
    `user_id`, `resume`, `highest_qualification`, `skills`, `nationality`, `experience`, `education`, 
    `full_name`, `email`, `phone`, `city`, `state`, `country`, `current_job_title`, `current_company`, 
    `total_experience`, `current_salary`, `expected_salary`, `preferred_location`, `job_type`, `notice_period`, 
    `linkedin_url`, `portfolio_url`, `profile_photo`, `date_of_birth`, `gender`, `is_deleted`, `added_by`, 
    `created_at`, `updated_at`
) VALUES (
    1, 
    'assets/uploads/resumes/john_doe_resume.pdf', 
    'Bachelor\'s Degree', 
    'PHP, JavaScript, MySQL, React, Node.js, Git, Agile, REST API, MongoDB', 
    'American', 
    '[{"company_name": "Tech Solutions Inc", "job_title": "Senior PHP Developer", "employment_type": "Full-time", "start_date": "2020-01-15", "end_date": "", "is_current": 1}, {"company_name": "Digital Agency", "job_title": "PHP Developer", "employment_type": "Full-time", "start_date": "2018-06-01", "end_date": "2019-12-31", "is_current": 0}]', 
    '[{"institution_name": "State University", "degree": "Bachelor of Computer Science", "year_of_passing": "2018", "grade": "3.8 GPA"}]', 
    'John Doe', 
    'john.doe@example.com', 
    '+1-555-0123', 
    'New York', 
    'New York', 
    'USA', 
    'Senior PHP Developer', 
    'Tech Solutions Inc', 
    '5.5', 
    '85000', 
    '95000', 
    'New York, San Francisco, Remote', 
    'Full-time', 
    '30 days', 
    'https://linkedin.com/in/johndoe', 
    'https://johndoe.dev', 
    'assets/uploads/profile_photos/john_doe.jpg', 
    '1992-05-15', 
    'Male', 
    0, 
    1, 
    NOW(), 
    NOW()
);

-- Insert test candidate 2 - Partial profile (for testing profile completion)
INSERT INTO `candidates`(
    `user_id`, `resume`, `highest_qualification`, `skills`, `nationality`, `experience`, `education`, 
    `full_name`, `email`, `phone`, `city`, `state`, `country`, `current_job_title`, `current_company`, 
    `total_experience`, `current_salary`, `expected_salary`, `preferred_location`, `job_type`, `notice_period`, 
    `linkedin_url`, `portfolio_url`, `profile_photo`, `date_of_birth`, `gender`, `is_deleted`, `added_by`, 
    `created_at`, `updated_at`
) VALUES (
    2, 
    NULL, 
    'Master\'s Degree', 
    'Python, Django, PostgreSQL', 
    'Canadian', 
    NULL, 
    '[{"institution_name": "University of Toronto", "degree": "Master of Computer Science", "year_of_passing": "2020", "grade": "3.9 GPA"}]', 
    'Jane Smith', 
    'jane.smith@example.com', 
    '+1-555-0124', 
    'Toronto', 
    'Ontario', 
    'Canada', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    '75000', 
    'Toronto, Remote', 
    'Full-time', 
    'Immediate', 
    NULL, 
    NULL, 
    NULL, 
    '1990-08-22', 
    'Female', 
    0, 
    1, 
    NOW(), 
    NOW()
);

-- Insert test candidate 3 - Fresh graduate profile
INSERT INTO `candidates`(
    `user_id`, `resume`, `highest_qualification`, `skills`, `nationality`, `experience`, `education`, 
    `full_name`, `email`, `phone`, `city`, `state`, `country`, `current_job_title`, `current_company`, 
    `total_experience`, `current_salary`, `expected_salary`, `preferred_location`, `job_type`, `notice_period`, 
    `linkedin_url`, `portfolio_url`, `profile_photo`, `date_of_birth`, `gender`, `is_deleted`, `added_by`, 
    `created_at`, `updated_at`
) VALUES (
    3, 
    'assets/uploads/resumes/mike_wilson_resume.pdf', 
    'Bachelor\'s Degree', 
    'HTML, CSS, JavaScript, React, Vue.js, Git', 
    'American', 
    '[]', 
    '[{"institution_name": "Community College", "degree": "Associate in Web Development", "year_of_passing": "2023", "grade": "3.5 GPA"}]', 
    'Mike Wilson', 
    'mike.wilson@example.com', 
    '+1-555-0125', 
    'Los Angeles', 
    'California', 
    'USA', 
    'Junior Web Developer', 
    NULL, 
    '0', 
    NULL, 
    '55000', 
    'Los Angeles, San Francisco, Remote', 
    'Full-time', 
    'Immediate', 
    'https://linkedin.com/in/mikewilson', 
    'https://mikewilson.dev', 
    NULL, 
    '1998-03-10', 
    'Male', 
    0, 
    1, 
    NOW(), 
    NOW()
);

-- Insert test candidate 4 - Experienced professional with multiple experiences
INSERT INTO `candidates`(
    `user_id`, `resume`, `highest_qualification`, `skills`, `nationality`, `experience`, `education`, 
    `full_name`, `email`, `phone`, `city`, `state`, `country`, `current_job_title`, `current_company`, 
    `total_experience`, `current_salary`, `expected_salary`, `preferred_location`, `job_type`, `notice_period`, 
    `linkedin_url`, `portfolio_url`, `profile_photo`, `date_of_birth`, `gender`, `is_deleted`, `added_by`, 
    `created_at`, `updated_at`
) VALUES (
    4, 
    'assets/uploads/resumes/sarah_brown_resume.pdf', 
    'PhD', 
    'Machine Learning, Python, TensorFlow, Data Science, Statistics, R, SQL, AWS', 
    'British', 
    '[{"company_name": "AI Research Lab", "job_title": "Senior Data Scientist", "employment_type": "Full-time", "start_date": "2019-03-01", "end_date": "", "is_current": 1}, {"company_name": "Tech Corp", "job_title": "Data Scientist", "employment_type": "Full-time", "start_date": "2017-01-15", "end_date": "2019-02-28", "is_current": 0}, {"company_name": "StartupXYZ", "job_title": "Junior Data Analyst", "employment_type": "Full-time", "start_date": "2015-06-01", "end_date": "2016-12-31", "is_current": 0}]', 
    '[{"institution_name": "Oxford University", "degree": "PhD in Computer Science", "year_of_passing": "2015", "grade": "First Class Honors"}, {"institution_name": "Imperial College London", "degree": "Master of Science", "year_of_passing": "2012", "grade": "Distinction"}]', 
    'Sarah Brown', 
    'sarah.brown@example.com', 
    '+44-20-1234-5678', 
    'London', 
    'England', 
    'UK', 
    'Senior Data Scientist', 
    'AI Research Lab', 
    '8.5', 
    '95000', 
    '120000', 
    'London, New York, Remote', 
    'Full-time', 
    '60 days', 
    'https://linkedin.com/in/sarahbrown', 
    'https://sarahbrown.ai', 
    'assets/uploads/profile_photos/sarah_brown.jpg', 
    '1988-11-28', 
    'Female', 
    0, 
    1, 
    NOW(), 
    NOW()
);

-- Insert test candidate 5 - Minimal profile (for testing empty states)
INSERT INTO `candidates`(
    `user_id`, `resume`, `highest_qualification`, `skills`, `nationality`, `experience`, `education`, 
    `full_name`, `email`, `phone`, `city`, `state`, `country`, `current_job_title`, `current_company`, 
    `total_experience`, `current_salary`, `expected_salary`, `preferred_location`, `job_type`, `notice_period`, 
    `linkedin_url`, `portfolio_url`, `profile_photo`, `date_of_birth`, `gender`, `is_deleted`, `added_by`, 
    `created_at`, `updated_at`
) VALUES (
    5, 
    NULL, 
    NULL, 
    NULL, 
    'American', 
    NULL, 
    NULL, 
    'Alex Johnson', 
    'alex.johnson@example.com', 
    NULL, 
    NULL, 
    NULL, 
    'USA', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    0, 
    1, 
    NOW(), 
    NOW()
);
